### ISSUE TITLE
Can no longer install from pip

### ISSUE THREAD

**Issue by ohlookemus** [jlfwong/flask_debugtoolbar_lineprofilerpanel#4]
```
pip install flask-debugtoolbar-lineprofilerpanel
Downloading/unpacking flask-debugtoolbar-lineprofilerpanel
  Downloading Flask-DebugToolbar-LineProfilerPanel-0.0.6.tar.gz
  Running setup.py egg_info for package flask-debugtoolbar-lineprofilerpanel

Requirement already satisfied (use --upgrade to upgrade): Flask-DebugToolbar in /Users/congqin/PythonVEs/fantex-global/lib/python2.7/site-packages (from flask-debugtoolbar-lineprofilerpanel)
Downloading/unpacking line-profiler (from flask-debugtoolbar-lineprofilerpanel)
  Could not find a version that satisfies the requirement line-profiler (from flask-debugtoolbar-lineprofilerpanel) (from versions: 1.0b1, 1.0b2, 1.0b3)
Cleaning up...
No distributions matching the version for line-profiler (from flask-debugtoolbar-lineprofilerpanel)
Storing complete log in /Users/congqin/.pip/pip.log
```

**Comment by divad12** [comment]
This is due to the following change in behavior in newer versions of `pip`:

> ## [Pre-release Versions](http://www.pip-installer.org/en/1.4.1/logic.html#pre-release-versions)
> 
> Starting with v1.4, pip will only install stable versions as specified by [PEP426](http://www.python.org/dev/peps/pep-0426) by default. If a version cannot be parsed as a compliant [PEP426](http://www.python.org/dev/peps/pep-0426) version then it is assumed to be a pre-release.
> 
> If a Requirement specifier includes a pre-release or development version (e.g. `>=0.0.dev0`) then pip will allow pre-release and development versions for that requirement. This does not include the `!=` flag.
> 
> The `pip install` command also supports a `–pre` flag that will enable installing pre-releases and development releases.

Since there are no stable versions of this package yet, you can use the `--pre` flag as a temporary workaround:

``` bash
pip install --pre flask-debugtoolbar-lineprofilerpanel
```

See [this StackOverflow answer](http://stackoverflow.com/a/18319230/392426) for more information.

**Comment by jlfwong** [comment]
So I'm guessing the right solution is just to push a stable version.

I'm on a cruddy internet connection at the moment, so I'll have to get back to this.

**Comment by jlfwong** [comment]
Ah, the problem was at least partially from one of the dependencies, not this package itself.

Shouldn't noticed from the line

```
  Could not find a version that satisfies the requirement line-profiler (from flask-debugtoolbar-lineprofilerpanel) (from versions: 1.0b1, 1.0b2, 1.0b3)
```

In any case, I just pushed 1.0.1 with a dependency specified and tried installing it locally. Should be good to go now.
