### ISSUE TITLE
It just keeps showing the instructions page 

### ISSUE THREAD

**Issue by simkessy** [jlfwong/flask_debugtoolbar_lineprofilerpanel#6]
I've installed it and set it as a decorator for a method but it just returns the instructions page every time: 

![image](https://user-images.githubusercontent.com/5871660/78412309-b5f69800-75c7-11ea-872b-7a0600cd0b29.png)

It says it's around 2 functions but I don't see any results

**Comment by jlfwong** [comment]
Hi @simkessy!

I literally haven't used this in 6 years, so I'm afraid I'm not going to be of much help here. Your best guess digging around the code is going to be as good as mine 😬

**Comment by simkessy** [comment]
Sounds good man, thank you
